---
- hosts: localhost
  roles:
    - git
    - { role: zsh, plugins: "git sublime composer symfony2 history history-substring-search" }
    - vim
    - php
    - apache

  tasks:
    # configuration of git
    - name: global .gitignore
      template: >
        src=templates/git/gitignore.j2
        dest={{ ansible_env.HOME }}/.gitignore
    - name: .gitconfig
      template: >
        src=templates/git/gitconfig.j2
        dest={{ ansible_env.HOME }}/.gitconfig
    # configuration of vim
    - name: .vimrc
      template: >
        src=templates/vim/vimrc.j2
        dest={{ ansible_env.HOME }}/.vimrc
