---

- name: tap homebrew/dupes
  homebrew_tap: tap=homebrew/dupes state=present

- name: tap homebrew/php
  homebrew_tap: tap=homebrew/php state=present

- name: install
  homebrew: >
    name=php56
    state=present
  notify:
   - restart apache

- name: packages
  homebrew: >
    name={{ item }}
    state=present
  with_items:
    - php56-xdebug
  notify:
   - restart apache

- name: enable in apache
  lineinfile: >
    dest=/etc/apache2/other/php5.conf
    line="LoadModule php5_module /usr/local/opt/php56/libexec/apache2/libphp5.so"
    insertbefore=BOF
  sudo: yes
  notify:
   - restart apache

- name: configure
  template: >
    src=zzz-config.ini.j2
    dest=/usr/local/etc/php/5.6/conf.d/zzz-config.ini
  sudo: yes
  notify:
   - restart apache
